services:
  - type: web
    name: scrape-plus-llm-extract-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
      - key: DEBUG_MODE
        value: "false"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/.cache/ms-playwright"
    healthCheckPath: /health
    autoDeploy: true 